-- MySQL Script generated by MySQL Workbench
-- Sat Dec 30 01:23:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tutor Accademico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tutor Accademico` (
  `email` VARCHAR(45) NOT NULL,
  `luogoNascita` VARCHAR(45) NULL,
  `codiceFiscale` VARCHAR(45) NULL,
  `dataNascita` VARCHAR(65) NULL,
  `cognome` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `dipartimento` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `via` VARCHAR(45) NULL,
  `residenza` VARCHAR(45) NULL,
  `sesso` VARCHAR(45) NULL,
  `codiceDocente` VARCHAR(45) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Studente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Studente` (
  `email` VARCHAR(45) NOT NULL,
  `luogoNascita` VARCHAR(45) NULL,
  `codiceFiscale` VARCHAR(45) NULL,
  `dataNascita` VARCHAR(65) NULL,
  `cognome` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `matricola` VARCHAR(45) NULL,
  `tipoLaurea` VARCHAR(45) NULL,
  `via` VARCHAR(45) NULL,
  `residenza` VARCHAR(45) NULL,
  `sesso` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Didattica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Didattica` (
  `email` VARCHAR(45) NOT NULL,
  `luogoNascita` VARCHAR(45) NULL,
  `codiceFiscale` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `dataNascita` VARCHAR(65) NULL,
  `cognome` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `direttore` SMALLINT(5) NULL,
  `via` VARCHAR(45) NULL,
  `residenza` VARCHAR(45) NULL,
  `sesso` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tirocinio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tirocinio` (
  `id` VARCHAR(65) NOT NULL,
  `stato` SMALLINT(5) NULL,
  `nome` VARCHAR(45) NULL,
  `obiettivi` VARCHAR(145) NULL,
  `descrizione` VARCHAR(345) NULL,
  `numPosti` INT NULL,
  `responsabile` VARCHAR(45) NULL,
  `sede` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `tutor` VARCHAR(65) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `emailTutTir`
    FOREIGN KEY (`tutor`)
    REFERENCES `mydb`.`Tutor Accademico` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Feedback` (
  `id` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id`),
  `data` DATE NULL,
  `commento` VARCHAR(225) NULL,
  `valutazione` INT NULL,
  `tirocinio` VARCHAR(65) NULL,
  `studente` VARCHAR(65) NULL,
  CONSTRAINT `IDTirFed`
    FOREIGN KEY (`tirocinio`)
    REFERENCES `mydb`.`Tirocinio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emailStudFed`
    FOREIGN KEY (`studente`)
    REFERENCES `mydb`.`Studente` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Richiede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Richiede` (
  `stato` VARCHAR(25) NOT NULL,
  `dataInvio` VARCHAR(60) NULL,
  `dataAccettazione` VARCHAR(60) NULL,
  `tirocinio` VARCHAR(65) NULL,
  `studente` VARCHAR(65) NULL,
  CONSTRAINT `idTir`
    FOREIGN KEY (`tirocinio`)
    REFERENCES `mydb`.`Tirocinio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emailStud`
    FOREIGN KEY (`studente`)
    REFERENCES `mydb`.`Studente` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Annuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Annuncio` (
  `titolo` VARCHAR(65) NOT NULL,
  `body` VARCHAR(2445) NULL,
  `data` VARCHAR(65) NULL,
  `filePosition` VARCHAR(100) NULL,
  `autore` VARCHAR(65) NULL,
  PRIMARY KEY (`titolo`),
  CONSTRAINT `emailAnn`
    FOREIGN KEY (`autore`)
    REFERENCES `mydb`.`Didattica` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
